baseURL                = "https://aries727.site/"
languageCode           = "zh-cn"
title                  = "Aries's Blog"
defaultContentLanguage = "zh-cn"
hasCJKLanguage         = true
theme                  = "hugo-theme-stack"
enableRobotsTXT        = true

disableKinds = ["taxonomy", "term"]

[outputs]
    home = ["html", "rss"]
    page = ["html"]
    section = ["html"]

[services]
    [services.rss]
        limit = 30

[pagination]
    pagerSize = 9999
    disableAliases = true

[permalinks]
    post = "/:sections/:contentbasename/"
    page = "/:slug/"
