baseURL                = "http://aries727.site/"
languageCode           = "zh-cn"
title                  = "Aries727's Blog"
defaultContentLanguage = "zh-cn"
hasCJKLanguage         = true
theme                  = "hugo-theme-stack"

disableKinds = ["taxonomy", "term", "RSS", "sitemap", "robotsTXT", "404"]

[pagination]
    pagerSize = 9999
    disableAliases = true

[permalinks]
    post = "/:sections/:filename/"
    page = "/:slug/"
