mainSections   = ["post"]
rssFullContent = true

[footer]
    since = 2025

[sidebar]
    emoji    = "🐏"
    subtitle = "计算机笔记 | 摄影作品 | 生活记录"

[article]
    math = true
    [article.license]
        enabled = true
        default = "Licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"

[widgets]
    homepage = []
    page = [{ type = "toc" }]

[comments]
    enabled  = false
    provider = ""
