mainSections   = ["post"]
rssFullContent = true

[footer]
    since = 2025

[sidebar]
    emoji    = "🐏"
    subtitle = "计算机笔记 | 摄影作品 | 生活记录"

[article]
    math = true
    readingTime = false
    [article.license]
        enabled = false

[widgets]
    homepage = []
    page = [{ type = "toc" }]

[comments]
    enabled  = false
    provider = ""

favicon = "img/favicon.jpg"
